### ISSUE TITLE
Right-click menu, copy and paste does not work

### ISSUE THREAD

**Issue by xuoutput** [suren-atoyan/monaco-react#208] opened 2021-03-17 12:20 UTC
**Describe the bug**

Right-click menu, copy and paste does not work

**To Reproduce**

https://codesandbox.io/s/monaco-editorreact---get-value-1hzz8

**Expected behavior**
fix copy and  paste

**Comment by suren-atoyan** [comment] 2021-03-17 20:23
Uploading Screen Recording 2021-03-18 at 00.16.28.mov…

I reckon it's related to your environment. Could you please check it in incognito mode? Maybe you have some specific extension that prevents mentioned actions.

**Comment by xuoutput** [comment] 2021-03-18 07:23
https://user-images.githubusercontent.com/16385443/111587864-bc444b00-87fd-11eb-9087-d1027bdf1901.mov

I mean to use the right-click menu, not the shortcut keys(ctrl+c, ctrl+v)

**Comment by SpaceComet** [comment] 2021-08-16 19:11
Hi @xuoutput I think that happens because your browser does not have permissions to get the clipboard information
![Screenshot 2021-08-16 150647](https://user-images.githubusercontent.com/38369407/129617028-01ec8636-ca9e-4ee0-87b0-f8853b60b973.jpg)


Maybe they asked you before and you clicked `Block`?

You can try to open it form a incognito windows and see if they ask you. If so then delete the configuration of that page in your browser.

I hope that helps. I don't think is monaco-react.

**Comment by suren-atoyan** [comment] 2022-09-28 03:05
@xuoutput I can confirm @Xoffio thesis. If you check it in the `monaco-react` [website](http://monaco-react.surenatoyan.com/) or `monaco-editor` [playground](https://microsoft.github.io/monaco-editor/playground.html) it will ask permission for this and after gaining that permission it will work as expected. For some reason, it doesn't ask in the codesandbox.

**Comment by suren-atoyan** [comment] 2022-09-28 03:06
I am closing this, but feel free to re-open it if it doesn't work in other places too.

**Closed by suren-atoyan** 2022-09-28 03:06 UTC
