### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by luhis** [suren-atoyan/monaco-react#35] opened 2019-11-14 23:11 UTC
I updated to v2.3.0 and now I get out of memory errors when i try to edit C#.

Example page:
https://codegolf.club/demo

just typing in random text in the Monaco editor will cause the out of memory error to happen.

**Comment by SurenAt93** [comment] 2019-11-15 10:07
<img width="1130" alt="Screen Shot 2019-11-15 at 14 00 45" src="https://user-images.githubusercontent.com/13118722/68934929-13bd4b80-07b1-11ea-8049-ee7b7986f8c0.png">

I see you had another change after updating the package version. Can I ask you to downgrade the package version, to be sure that the problem is definitely in the new version? And also please note which one is the latest "right" working version of the package.

Thank you!

**Comment by SurenAt93** [comment] 2019-11-15 10:32
Why I am asking this is because [here](https://codesandbox.io/s/monaco-editorreact---controlled-editor-yg5il?fontsize=14&hidenavigation=1&theme=dark) is an example of ControlledEditor (which you are using) in version 2.3.0, and, as I saw, everything is okay so far.

**Comment by luhis** [comment] 2019-11-16 10:01
you are right, rolling back React Monaco doesn't fix it.  I can see what's happening now.  It keeps emitting on change events, so it creates a feedback loop and runs away.  I can see in the logs that the loops are alternating last char missing, last char present. I will probably just move to the uncontrolled input and that should solve the problem

**Comment by SurenAt93** [comment] 2019-11-18 08:50
Okay. And Please let me know if everything is okay, and we can close the issue.

**Comment by luhis** [comment] 2019-11-19 08:01
so, i have left it as the controlled editor, but just removed the feedback of the state into the Editor component, so it is no longer crashing, but I don't think it is working correctly.  I will have another look at it when i have some time

**Closed** 2020-11-19 00:00 UTC
